Repository AY2223S1-CS2103T-T15-2/tp, pull requests merged in 2022-10, with the labels that each got.

#97 [User Guide] Update delete command examples and command summary in user guide
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#95 [Development] Refactor list to viewAll command #96
  src/main/java/seedu/address/logic/commands/ViewAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ViewAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.HIGH, type.Task

#92 [#85] Edit Duplicate Person error message in EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.HIGH, type.Story

#98 [User Story] Add new id field to Person
  src/main/java/seedu/address/model/person/Id.java
Labels: priority.HIGH, type.Story

#94 [Implementation] Feature View
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.HIGH, type.Story

#93 [#69] [#70] Feature viewAll
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewAllCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/FilteredStudents.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/commands/AddStudCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/FilteredStudentsTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
Labels: priority.HIGH, type.Story, type.Task

#91 [#77] Implement new DeleteCommand to delete individual student records
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/student/IdPredicate.java
  src/main/java/seedu/address/model/student/NamePredicate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddStudCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentRecordParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: priority.HIGH, type.Story

#101 [#78] Rename instances of AddressBook to StudentRecord in Storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/storage/JsonSerializableStudentRecord.java
  src/main/java/seedu/address/storage/JsonStudentRecordStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/StudentRecordStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonStudentRecordStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.HIGH, type.Story

#104 [User Guide] Update UG with new addstud command details
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.documentation, doc.UG, type.Story

#103 [#81] [#82] Implement view feature for v1.2
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentRecordParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/StudentRecordParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.HIGH, type.Story, type.Task

#106 [#102][User Story] As an intermediate user, I can view a list of students by class
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddStudCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewClassCommand.java
  src/main/java/seedu/address/logic/parser/AddStudCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StudentRecordParser.java
  src/main/java/seedu/address/logic/parser/ViewClassCommandParser.java
  src/main/java/seedu/address/model/student/Class.java
  src/main/java/seedu/address/model/student/ClassPredicate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewClassCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ViewClassCommandParserTest.java
  src/test/java/seedu/address/model/student/ClassPredicateTest.java
  src/test/java/seedu/address/model/student/ClassTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.HIGH, type.Story

#109 [#108] [User Guide] Update view command format in user guide
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#110 [#72] Update the user story to explain the need for viewAll functionality
  docs/DeveloperGuide.md
Labels: doc.DG, type.Task

#114 [#112] Fix command format and update user guide for DeleteCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentRecordParserTest.java
Labels: type.documentation, priority.HIGH, doc.UG, type.Bug, severity.Low

#115 [#107][User Guide] Update user guide with ViewClass Command
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#116 [Release] Update version number for release
  src/main/java/seedu/address/MainApp.java
Labels: priority.HIGH, type.Task

#118 [Release] Update jar file name for release
  build.gradle
Labels: priority.HIGH, type.Task

#120 [#79] Update ClearCommand success message and command summary table
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: type.documentation, priority.HIGH, doc.UG, type.Story

#126 [Developer Guide] Update developer guide structure
  docs/DeveloperGuide.md
Labels: type.documentation, priority.HIGH, doc.DG

#127 [#125] [Enhancement] Rename View command to Find
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentRecordParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentRecordParserTest.java
Labels: priority.HIGH, type.Enhancement

#130 [Task] Enable assertions and update version number
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: priority.HIGH, type.Task

#129 [#128] [Bug] Remove occurrences of "AB3" or "AddressBook" from code
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableStudentRecordTest/duplicateStudentRecord.json
  src/test/data/JsonSerializableStudentRecordTest/invalidStudentRecord.json
  src/test/data/JsonSerializableStudentRecordTest/typicalStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/invalidAndValidStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/invalidStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/notJsonFormatStudentRecord.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/StudentRecordTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonSerializableStudentRecordTest.java
  src/test/java/seedu/address/storage/JsonStudentRecordStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Bug, severity.Low

#139 [#133][#138] Changes to AddStudCommand and Student Fields
  src/main/java/seedu/address/logic/commands/AddStudCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddStudCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Address.java
  src/main/java/seedu/address/model/student/Class.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableStudentRecordTest/duplicateStudentRecord.json
  src/test/data/JsonSerializableStudentRecordTest/invalidStudentRecord.json
  src/test/data/JsonSerializableStudentRecordTest/typicalStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/invalidAndValidStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/invalidStudentRecord.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddStudCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/StudentRecordTest.java
  src/test/java/seedu/address/model/student/AddressTest.java
  src/test/java/seedu/address/model/student/ClassPredicateTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/NameTest.java
  src/test/java/seedu/address/model/student/PhoneTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.HIGH, type.Enhancement

#141 [User Guide] Update user guide structure
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#136 [#123] Implement Toggle View Command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ToggleViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewAllCommand.java
  src/main/java/seedu/address/logic/parser/StudentRecordParser.java
  src/main/java/seedu/address/model/FilteredStudents.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/test/java/seedu/address/logic/commands/AddStudCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ToggleViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAllCommandTest.java
  src/test/java/seedu/address/logic/parser/StudentRecordParserTest.java
  src/test/java/seedu/address/model/FilteredStudentsTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.HIGH, type.Story

#144 [#143][Developer Guide] Add ViewClass Command into Developer Guide
  docs/DeveloperGuide.md
Labels: type.documentation, priority.HIGH, doc.DG

#135 [#124] Update Student Card UI
  src/main/java/seedu/classify/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
Labels: priority.MEDIUM, type.Task

#121 [#66] Implement Exam class for managing academic records
  build.gradle
  src/main/java/seedu/classify/logic/commands/AddStudCommand.java
  src/main/java/seedu/classify/logic/commands/EditCommand.java
  src/main/java/seedu/classify/logic/parser/AddStudCommandParser.java
  src/main/java/seedu/classify/logic/parser/CliSyntax.java
  src/main/java/seedu/classify/logic/parser/EditCommandParser.java
  src/main/java/seedu/classify/logic/parser/ParserUtil.java
  src/main/java/seedu/classify/model/student/Student.java
  src/main/java/seedu/classify/model/tag/Exam.java
  src/main/java/seedu/classify/model/tag/Tag.java
  src/main/java/seedu/classify/model/util/SampleDataUtil.java
  src/main/java/seedu/classify/storage/JsonAdaptedExam.java
  src/main/java/seedu/classify/storage/JsonAdaptedStudent.java
  src/main/java/seedu/classify/storage/JsonAdaptedTag.java
  src/main/java/seedu/classify/ui/StudentCard.java
  src/test/data/JsonSerializableStudentRecordTest/duplicateStudentRecord.json
  src/test/data/JsonSerializableStudentRecordTest/invalidStudentRecord.json
  src/test/data/JsonSerializableStudentRecordTest/typicalStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/invalidAndValidStudentRecord.json
  src/test/data/JsonStudentRecordStorageTest/invalidStudentRecord.json
  src/test/java/seedu/classify/logic/LogicManagerTest.java
  src/test/java/seedu/classify/logic/commands/CommandTestUtil.java
  src/test/java/seedu/classify/logic/commands/EditCommandTest.java
  src/test/java/seedu/classify/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/classify/logic/parser/AddStudCommandParserTest.java
  src/test/java/seedu/classify/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/classify/logic/parser/ParserUtilTest.java
  src/test/java/seedu/classify/model/StudentRecordTest.java
  src/test/java/seedu/classify/model/student/StudentTest.java
  src/test/java/seedu/classify/model/student/UniqueStudentListTest.java
  src/test/java/seedu/classify/model/tag/ExamTest.java
  src/test/java/seedu/classify/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/classify/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/classify/testutil/StudentBuilder.java
  src/test/java/seedu/classify/testutil/StudentUtil.java
  src/test/java/seedu/classify/testutil/TypicalStudents.java
Labels: priority.HIGH, type.Story, type.Epic

#146 [UI] Update student card UI with grades
  docs/DeveloperGuide.md
  src/main/java/seedu/classify/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
Labels: doc.DG, type.Enhancement, severity.VeryLow

#148 [User Guide] Update features and command summary sections
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#157 [Developer Guide] Add implementation details for delete command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/images/DeleteCommandSequenceDiagram.png
Labels: type.documentation, doc.DG

#155 Update Structure of UG
  docs/UserGuide.md
Labels: type.documentation, doc.DG

#160 [Developer Guide] Update architecture section of developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.documentation, doc.DG

#156 [#153] [User Guide] Update toggleView and viewAll feature in User Guide
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#164 [Code Quality] Fix DeleteCommand bug and improve code quality
  src/main/java/seedu/classify/logic/commands/DeleteCommand.java
  src/main/java/seedu/classify/logic/commands/ExitCommand.java
  src/main/java/seedu/classify/logic/commands/FindCommand.java
  src/main/java/seedu/classify/logic/commands/HelpCommand.java
  src/main/java/seedu/classify/logic/commands/ViewAllCommand.java
  src/main/java/seedu/classify/logic/commands/ViewClassCommand.java
  src/main/java/seedu/classify/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/classify/model/student/Id.java
  src/test/java/seedu/classify/storage/JsonStudentRecordStorageTest.java
Labels: type.Bug, severity.Medium

#165 Update overall UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/fonts/RobotoMono-Light.ttf
  src/main/resources/view/fonts/RobotoMono-Regular.ttf
  src/main/resources/view/fonts/RobotoMono-SemiBold.ttf
Labels: type.Task

#169 [#168] [Bug] FindCommand to throw error when ID field not in the correct format
  src/main/java/seedu/classify/logic/parser/FindCommandParser.java
Labels: type.Bug, severity.Medium

#166 [#167][Developer Guide] Update use cases
  docs/DeveloperGuide.md
Labels: type.documentation, doc.DG

#163 [Developer Guide] Update instructions for manual testing
  docs/DeveloperGuide.md
Labels: type.documentation, doc.DG

#170 [UI] Improve UI layout and scaling
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, severity.Low

#172 [#171][Enhancement][Bug] Add more test cases and change ViewClass success message
  src/main/java/seedu/classify/MainApp.java
  src/main/java/seedu/classify/commons/core/Messages.java
  src/main/java/seedu/classify/logic/commands/EditCommand.java
  src/main/java/seedu/classify/logic/commands/ViewClassCommand.java
  src/main/java/seedu/classify/storage/StorageManager.java
  src/test/java/seedu/classify/logic/LogicManagerTest.java
  src/test/java/seedu/classify/logic/commands/AddStudCommandIntegrationTest.java
  src/test/java/seedu/classify/logic/commands/AddStudCommandTest.java
  src/test/java/seedu/classify/logic/commands/ViewClassCommandIntegrationTest.java
  src/test/java/seedu/classify/logic/commands/ViewClassCommandTest.java
  src/test/java/seedu/classify/logic/parser/ParserUtilTest.java
  src/test/java/seedu/classify/logic/parser/ViewClassCommandParserTest.java
  src/test/java/seedu/classify/storage/JsonStudentRecordStorageTest.java
Labels: priority.HIGH, type.Enhancement, type.Bug, severity.VeryLow

#178 [Developer Guide] Update UML diagrams in architecture section
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.documentation, doc.DG

#179 [Enhancement] Update DeleteCommandParser to use ArgumentMultimap
  src/main/java/seedu/classify/commons/core/Messages.java
  src/main/java/seedu/classify/logic/parser/DeleteCommandParser.java
Labels: type.Enhancement

#181 [User Guide] Add viewStats command to command summary table
  docs/UserGuide.md
Labels: type.documentation, doc.UG

#149 [#147] [Development] Implement ViewStats feature
  src/main/java/seedu/classify/commons/core/Messages.java
  src/main/java/seedu/classify/logic/commands/ViewAllCommand.java
  src/main/java/seedu/classify/logic/commands/ViewStatsCommand.java
  src/main/java/seedu/classify/logic/parser/CliSyntax.java
  src/main/java/seedu/classify/logic/parser/ParserUtil.java
  src/main/java/seedu/classify/logic/parser/StudentRecordParser.java
  src/main/java/seedu/classify/logic/parser/ViewStatsCommandParser.java
  src/main/java/seedu/classify/model/FilteredStudents.java
  src/main/java/seedu/classify/model/Model.java
  src/main/java/seedu/classify/model/ModelManager.java
  src/main/java/seedu/classify/model/StudentRecord.java
  src/main/java/seedu/classify/model/student/GradeComparator.java
  src/main/java/seedu/classify/model/student/GradeLessThanMeanPredicate.java
  src/main/java/seedu/classify/model/student/NameComparator.java
  src/main/java/seedu/classify/model/student/Student.java
  src/main/java/seedu/classify/model/student/UniqueStudentList.java
  src/main/java/seedu/classify/model/student/exceptions/ExamNotFoundException.java
  src/main/java/seedu/classify/model/tag/Exam.java
  src/test/java/seedu/classify/logic/commands/AddStudCommandTest.java
  src/test/java/seedu/classify/logic/commands/ViewStatsCommandTest.java
  src/test/java/seedu/classify/logic/parser/ParserUtilTest.java
  src/test/java/seedu/classify/logic/parser/StudentRecordParserTest.java
  src/test/java/seedu/classify/logic/parser/ViewStatsCommandParserTest.java
  src/test/java/seedu/classify/model/student/GradeComparatorTest.java
  src/test/java/seedu/classify/model/student/GradeLessThanMeanPredicateTest.java
Labels: priority.HIGH, type.Epic

#185 [#154] Update use case and user profile
  docs/DeveloperGuide.md
Labels: type.documentation, doc.DG

#187 [#186] [User Guide] Add details for ViewStats command
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#182 [Enhancement] Rename AddStudCommand to AddStudentCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/classify/logic/commands/AddStudentCommand.java
  src/main/java/seedu/classify/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/classify/logic/parser/StudentRecordParser.java
  src/test/java/seedu/classify/logic/LogicManagerTest.java
  src/test/java/seedu/classify/logic/commands/AddStudentCommandIntegrationTest.java
  src/test/java/seedu/classify/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/classify/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/classify/logic/parser/StudentRecordParserTest.java
  src/test/java/seedu/classify/testutil/StudentUtil.java
Labels: type.Enhancement

#188 Add test cases for Exam class
  src/test/java/seedu/classify/model/tag/ExamTest.java
Labels: type.Task

#150 [#122] [Enhancement] Update HelpCommand to display command summary table
  src/main/java/seedu/classify/logic/commands/HelpCommand.java
  src/main/java/seedu/classify/ui/HelpWindow.java
  src/main/resources/images/command_summary_table.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.MEDIUM, type.Enhancement

#189 [Enhancement] Rename package and make command case insensitive
  src/main/java/seedu/classify/logic/commands/EditCommand.java
  src/main/java/seedu/classify/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/classify/logic/parser/EditCommandParser.java
  src/main/java/seedu/classify/logic/parser/ParserUtil.java
  src/main/java/seedu/classify/model/exam/Exam.java
  src/main/java/seedu/classify/model/student/Student.java
  src/main/java/seedu/classify/model/util/SampleDataUtil.java
  src/main/java/seedu/classify/storage/JsonAdaptedExam.java
  src/main/java/seedu/classify/storage/JsonAdaptedStudent.java
  src/test/java/seedu/classify/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/classify/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/classify/logic/parser/ParserUtilTest.java
  src/test/java/seedu/classify/logic/parser/ViewStatsCommandParserTest.java
  src/test/java/seedu/classify/model/exam/ExamTest.java
  src/test/java/seedu/classify/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/classify/testutil/StudentBuilder.java
  src/test/java/seedu/classify/testutil/StudentUtil.java
Labels: priority.MEDIUM, type.Enhancement, severity.Medium

#191 [#190] Bug fix toggle view
  src/main/java/seedu/classify/logic/commands/DeleteCommand.java
  src/main/java/seedu/classify/logic/commands/EditCommand.java
  src/main/java/seedu/classify/logic/commands/FindCommand.java
  src/main/java/seedu/classify/logic/commands/ToggleViewCommand.java
  src/main/java/seedu/classify/logic/commands/ViewAllCommand.java
  src/main/java/seedu/classify/logic/commands/ViewClassCommand.java
  src/main/java/seedu/classify/logic/commands/ViewStatsCommand.java
  src/main/java/seedu/classify/model/Model.java
  src/main/java/seedu/classify/model/ModelManager.java
  src/main/java/seedu/classify/ui/MainWindow.java
  src/main/java/seedu/classify/ui/StudentListPanel.java
  src/test/java/seedu/classify/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/classify/logic/commands/ToggleViewCommandTest.java
  src/test/java/seedu/classify/model/ModelManagerTest.java
  src/test/java/seedu/classify/model/student/IdTest.java
Labels: type.Bug, severity.High

#177 [#176] [Developer Guide] Update implementation details for FindCommand and ViewStatsCommand
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/ViewStatsCommandSequenceDiagram.puml
  docs/images/FindCommandActivityDiagram.png
  docs/images/ViewStatsCommandSequenceDiagram.png
Labels: type.documentation, priority.HIGH, doc.DG

#192 [User Guide] Standardise command format and add ToggleView screenshots
  docs/UserGuide.md
  docs/images/ToggleViewConcise.png
  docs/images/ToggleViewDetailed.png
Labels: type.documentation, doc.UG

#196 [Enhancement] Update command summary table image
  src/main/resources/images/command_summary_table.png
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement

#197 [#198] [Bug] Bugfix edit command
  src/main/java/seedu/classify/logic/commands/EditCommand.java
  src/main/java/seedu/classify/model/Model.java
  src/main/java/seedu/classify/model/ModelManager.java
  src/main/java/seedu/classify/model/StudentRecord.java
  src/main/java/seedu/classify/model/student/UniqueStudentList.java
  src/test/java/seedu/classify/logic/commands/AddStudentCommandTest.java
Labels: type.Bug, severity.Medium

#199 [Bug][Enhancement] Made some display message changes and fix ViewStats Bug
  docs/UserGuide.md
  src/main/java/seedu/classify/commons/core/Messages.java
  src/main/java/seedu/classify/logic/commands/FindCommand.java
  src/main/java/seedu/classify/logic/commands/ViewStatsCommand.java
  src/main/java/seedu/classify/model/student/Email.java
  src/main/java/seedu/classify/model/student/Name.java
  src/main/java/seedu/classify/model/student/Phone.java
  src/main/java/seedu/classify/model/student/Student.java
  src/test/java/seedu/classify/logic/commands/FindCommandTest.java
  src/test/java/seedu/classify/logic/commands/ViewStatsCommandTest.java
Labels: priority.HIGH, type.Enhancement, type.Bug

#200 [Bug] Fix bug with GradeComparator
  src/main/java/seedu/classify/model/student/GradeComparator.java
  src/test/java/seedu/classify/model/student/GradeComparatorTest.java
Labels: type.Bug, severity.Medium

#195 [#183][#184][Developer Guide] Update Product Scope, Non-Functional Requirements, Glossary and ViewClassCommand implementation
  docs/DeveloperGuide.md
  docs/diagrams/ViewClassCommandSequenceDiagram.puml
  docs/images/ViewClassCommandSequenceDiagram.png
Labels: type.documentation, priority.HIGH, doc.DG

#240 [Documentation][User Guide] Change Command Format description in User Guide
  docs/UserGuide.md
Labels: type.documentation, priority.HIGH, doc.UG

#239 [User Guide] Add clarification and emphasis in AddStudent section
  docs/UserGuide.md
Labels: type.documentation, doc.UG, severity.Medium

#242 [User Guide] Refine Find Command and ViewStats Command description
  docs/UserGuide.md
Labels: type.documentation, doc.UG

#243 [User Guide] Added section to introduce application layout and their functions
  docs/UserGuide.md
  docs/images/ClassifyApplicationWindow.png
Labels: type.documentation, doc.UG

#244 [Enhancement] Update command summary table image
  src/main/resources/images/command_summary_table.png
Labels: type.Enhancement

#241 [User Guide] Add caution note for delete command and screenshot for help command
  docs/UserGuide.md
  docs/images/HelpWindow.png
Labels: type.documentation, doc.UG

#245 Update link to section
  docs/UserGuide.md
Labels: type.documentation, doc.UG
