Repository AY2223S1-CS2103T-T15-2/tp, pull requests merged in 2022-09, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation, good first issue

#12 [#7] Add personal profile information for About Us page
  docs/AboutUs.md
  docs/images/danielk0k.png
  docs/team/danielkok.md
Labels: documentation, type.AboutUs

#14 [#9] Update user guide content for new student command
  docs/UserGuide.md
Labels: documentation, type.UG

#21 [#17] Update About Us with profile details
  docs/AboutUs.md
  docs/images/maxtance.png
  docs/team/maxtance.md
Labels: documentation, type.AboutUs

#22 [#18] Add the 'view all' command description to the UG
  docs/UserGuide.md
Labels: documentation, type.UG

#15 [#11] Add in user stories table in developer guide
  docs/DeveloperGuide.md
Labels: documentation, type.DG

#28 [#24] Upload profile photo and update personal details
  docs/AboutUs.md
  docs/images/jeromepui.png
  docs/team/jeromepui.md
Labels: documentation, priority.HIGH, type.AboutUs

#29 Update Glossary in DG
  docs/DeveloperGuide.md
Labels: type.DG

#30 [#25] Update descriptions for deleting student record and saving data
  docs/UserGuide.md
Labels: documentation, priority.HIGH, type.UG

#34 [#27] Create skeletal PPP (Jerome)
  docs/team/jeromepui.md
Labels: documentation, priority.HIGH, type.PPP

#36 [#26] Update non-functional requirements
  docs/DeveloperGuide.md
Labels: documentation, priority.HIGH, type.DG

#37 [#31] [About Us] Add profile picture and self-introduction in AboutUs Page
  docs/AboutUs.md
  docs/images/linuschan.png
Labels: documentation, priority.HIGH, type.AboutUs

#13 [#8] Update README with latest Ui mockup and project details
  README.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
Labels: documentation, type.README, type.Jekyll

#38 [#33][PPP] Create Skeletal PPP (Linus)
  docs/AboutUs.md
  docs/team/linuschancs.md
Labels: documentation, priority.HIGH, type.PPP

#39 [#32][User Guide] Add description for Edit feature
  docs/UserGuide.md
Labels: documentation, priority.HIGH, type.UG

#43 [#41] [About Us] Add profile picture and personal details
  docs/AboutUs.md
  docs/team/johndoe.md
  docs/team/minjiunn.md
Labels: documentation, priority.HIGH, type.AboutUs

#44 [#35][Developer Guide] Add Target User Profile and Edit Feature Use Case
  docs/DeveloperGuide.md
Labels: documentation, priority.HIGH, type.DG

#51 [About Us] Edit link to my PPP
  docs/AboutUs.md
Labels: priority.HIGH, type.AboutUs

#47 [#46][#48] [User Guide] Add description for view feature, Add command summary table
  docs/UserGuide.md
Labels: documentation, priority.HIGH, type.UG

#52 [#45][About Us] Rename Profile Picture to Github Username
  docs/AboutUs.md
  docs/images/linuschancs.png
Labels: documentation, type.AboutUs

#50 [#49] [PPP] Add skeletal PPP (minjiun)
  docs/team/minjiunn.md
Labels: documentation, priority.HIGH, type.PPP

#54 [#53] [Developer Guide] Add value proposition
  docs/DeveloperGuide.md
Labels: documentation, priority.HIGH, type.DG

#56 [UserGuide] Remove help command and update clear command
  docs/UserGuide.md
  docs/_config.yml
Labels: bug, type.UG

#59 [README] Remove AB3 traces
  README.md
Labels: bug, priority.HIGH, type.README

#62 [#61] Update quick start section with Class-ify details
  docs/UserGuide.md
Labels: documentation, priority.HIGH, type.UG

#58 [#57] Update index.md with Class-ify description
  docs/index.md
Labels: documentation, priority.HIGH

#60 [#55][User Guide] Add Class-ify overview into user guide and delete Command Format segment
  docs/UserGuide.md
Labels: documentation, type.UG

#63 Update FAQ of UG and Glossary of DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.UG, type.DG

#64 Update build badges for README.md and index.md
  README.md
  docs/index.md
Labels: type.README, type.Jekyll
